---
title: Kopieer code van de ene sprite naar de andere
hero_image: images/banner.png
description: Sleep code van het codegebied van een sprite naar een andere sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Kopieer code van de ene sprite naar de andere
