---
title: एक sprite पासून दुसऱ्यामध्ये कोड कॉपी करा
hero_image: images/banner.png
description: एका स्प्राईटच्या Code एरियामधून दुसऱ्यामध्ये स्प्राईटमध्ये कोड ड्रॅग करा
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: एक sprite पासून दुसऱ्यामध्ये कोड कॉपी करा
