---
title: एक स्प्राइट से दूसरे स्प्राइट में कोड कॉपी करें
hero_image: images/banner.png
description: एक स्प्राइट के Code क्षेत्र से दूसरे स्प्राइट में कोड खींचें
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: एक स्प्राइट से दूसरे स्प्राइट में कोड कॉपी करें
