---
title: ఒక sprite నుండి మరొకదానికి కోడ్‌ను కాపీ చేయండి
hero_image: images/banner.png
description: ఒక sprite Code ప్రాంతం నుండి మరొక sprite కి కోడ్‌ని డ్రాగ్ చేయండి
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: ఒక sprite నుండి మరొకదానికి కోడ్‌ను కాపీ చేయండి
