---
title: Khuphela ikhowudi ukusuka kwi-sprite ukuya kwesinye
hero_image: images/banner.png
description: Tsala ikhowudi kwindawo yeKhowudi yesprite esinye uyibeke kwindawo yeKhowudi kwesinye i-sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Khuphela ikhowudi ukusuka kwi-sprite ukuya kwesinye
