---
title: Kopiraj kôd s jednog lika na drugi
hero_image: images/banner.png
description: Povuci kôd iz područja kôda jednog lika u drugi lik
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Kopiraj kôd s jednog lika na drugi
