---
title: Copïo cod o un corlun i'r llall
hero_image: images/banner.png
description: Llusgo cod o ardal Cod un corlun i corlun arall
version: 3
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Copïo cod o un corlun i'r llall
