---
title: Kopiere Code von einer Figur zu einer anderen
hero_image: images/banner.png
description: Ziehe den Code aus dem Codebereich einer Figur in eine andere Figur
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Kopiere Code von einer Figur zu einer anderen
