---
title: Copie o código de um ator para outro
hero_image: images/banner.png
description: Arraste o código da área de código de um ator para outro ator
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Copie o código de um ator para outro
