---
title: Copiar código de un objeto a otro
hero_image: images/banner.png
description: Arrastra el código del área de código de un objeto a otro
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Copiar código de un objeto a otro
