---
title: Skopiuj kod z jednego duszka do drugiego
hero_image: images/banner.png
description: Przeciągnij kod z obszaru Skrypt jednego duszka do innego duszka
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - title: Skopiuj kod z jednego duszka do drugiego
