---
title: Kopiera kod fr책n en sprajt till en annan
hero_image: images/banner.png
description: Dra kod fr책n en sprajts kodomr책de till en annan sprajts
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Kopiera kod fr책n en sprajt till en annan
