---
title: Copier le code d'un sprite à un autre
hero_image: images/banner.png
description: Faire glisser le code de la zone de code d'un sprite vers un autre sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Copier le code d'un sprite à un autre
