---
title: Copier le code d'un sprite à un autre
hero_image: images/banner.png
description: Drag code from the Code area of one sprite to another sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Copy code from one sprite to another
