---
title: Copia il codice da uno sprite all'altro
hero_image: images/banner.png
description: Trascina il codice dall'area codice di uno sprite a un altro sprite
version: 4
listed: false
copyedit: false
last_tested: "2021-03-23"
steps:
  - 
    title: Copia il codice da uno sprite all'altro
